### ISSUE TITLE
Create Models

### ISSUE THREAD

**Issue by altheasmith** [babybills-2015/CMBS_Project#1]
Deal
Loan
Property
Keywords
News Articles

**Comment by altheasmith** [comment]
Deal has many loans
Loans can have more than one deal

**Comment by altheasmith** [comment]
Loan has many properties

**Comment by altheasmith** [comment]
Keywords - many to many with news articles

**Comment by azjones227** [comment]
a rough draft of the models has been added to the project.

**Comment by altheasmith** [comment]
Models are created!
